### ISSUE TITLE
Would it be a hassle to update it to Slim 4?

### ISSUE THREAD

**Issue by ffuentese** [Voltra/slim-vue-app#8]
I noticed Slim 4 was released a while ago and I like Slim but I don't know if it'd break anything, for instance, in this project.-

**Comment by Voltra** [comment]
Sorry for the late reply, github never lets me know when I have a new issue opened for some reason.

v2.0.0 Migrates the project to Slim 4, with some major inconvenience due to all the changes in the core of Slim. Everything has been ported back though.

I'll close the issue for now, if anything feels weird because of the new version (or still needs to be updated) I'll be happy to reopen it and add to it.
